// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"mall/service/wxuser/rpc/internal/logic"
	"mall/service/wxuser/rpc/internal/svc"
	"mall/service/wxuser/rpc/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) AppLogin(ctx context.Context, in *user.AppLoginRequest) (*user.AppLoginResponse, error) {
	l := logic.NewAppLoginLogic(ctx, s.svcCtx)
	return l.AppLogin(in)
}

func (s *UserServer) UserInfo(ctx context.Context, in *user.UserInfoRequest) (*user.UserInfoResponse, error) {
	l := logic.NewUserInfoLogic(ctx, s.svcCtx)
	return l.UserInfo(in)
}
