// Code generated by goctl. DO NOT EDIT.
package types

type AppLoginRequest struct {
	AppId    string `json:"appId"`
	Code     string `json:"code"`
	Nickname string `json:"nickname"`
}

type AppLoginResponse struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	Message      string `json:"message"`
	Result_code  int64  `json:"result_code"`
}

type UserInfoResponse struct {
	Id       int64  `json:"id"`
	OpenId   string `json:"openId"`
	Name     string `json:"name"`
	NickName string `json:"nickName"`
	Gender   int64  `json:"gender"`
	Mobile   string `json:"mobile"`
}
